archives:
  - format: binary
builds:
  - goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}.sha256"
release:
  draft: true
  extra_files:
    - glob: ./release/web*
