services:
  web:
    image: ghcr.io/wormi4ok/menuplanner-web:latest
    depends_on:
      - api
    environment:
      API_ADDRESS: http://localhost:8081
#      MP_CLIENT_ID: ""
    ports:
      - 8080:80
    restart: unless-stopped
  api:
    image: ghcr.io/wormi4ok/menuplanner:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      MP_MYSQL_DSN: menuplanner:menuplanner@tcp(db:3306)/menuplanner?charset=utf8mb4&parseTime=True&loc=Local
      MP_JWT_SECRET: change-me-before-exposing-this-to-anyone
#      MP_CLIENT_ID: ""
#      MP_CLIENT_SECRET: ""
    ports:
      - 8081:8081
    restart: unless-stopped
  db:
    image: mysql:8.4
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: unsecurepassword
      MYSQL_DATABASE: menuplanner
      MYSQL_USER: menuplanner
      MYSQL_PASSWORD: menuplanner
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1' ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
