services:
  web:
    build:
      context: web
      target: dev
    volumes:
      - ./web/src:/app/src
    ports:
      - 127.0.0.1:8080:8080
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/wormi4ok/menuplanner
    ports:
      - 127.0.0.1:8081:8081
    restart: always
    environment:
      MP_HOST: 0.0.0.0
      MP_JWT_SECRET: menuplanner-supersecret
