name: CI

on:
  push:
    branches:
      - "!*"
    tags:
      - '*'

jobs:
  build-web:
    defaults:
      run:
        working-directory: web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Check code-style
        run: npm run lint
      - name: Build project
        run: |
          npm run build
          cd ..
          mkdir release
          tar -czf release/web.tar.gz web/dist
          shasum -a 256 release/web.tar.gz > release/web.tar.gz.sha256
          zip -r release/web.zip web/dist
          shasum -a 256 release/web.zip > release/web.zip.sha256
      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: web-ui
          path: release
  build-api:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      #      - name: Test
      #        run: go test ./...
      - name: Download Web UI artifact
        uses: actions/download-artifact@v2
        with:
          name: web-ui
          path: release
      - name: Build API docs
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: generate -i api.yml -g html2 -o docs
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
